import { Roboto, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/providers/theme-provider";
import StoreProvider from "@/components/providers/store-provider";
import { Toaster } from "sonner";



const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // optional but recommended
});


export const metadata = {
  title: "PaharTheke",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        {/* <ThemeProvider> */}
          <StoreProvider>
            {children}
            <Toaster
              position="top-right"
              richColors
              closeButton
              toastOptions={{
                className: "rounded-xl",
              }}
            />
          </StoreProvider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
