import { Roboto, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import StoreProvider from "@/components/providers/store-provider";
import { Toaster } from "sonner";



const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"], // optional but recommended
});


export const metadata = {
  title: "PaharTheke",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <StoreProvider>
          <Suspense fallback={
            <div className="min-h-screen flex items-center justify-center">
              <div className="h-10 w-10 border-4 border-green-200 border-t-green-700 rounded-full animate-spin" />
            </div>
          }>
            {children}
          </Suspense>
          <Toaster
            position="top-right"
            richColors
            closeButton
            toastOptions={{
              className: "rounded-xl",
            }}
          />
        </StoreProvider>
      </body>
    </html>
  );
}
