module.exports = {
  apps: [
    {
      name: "pos-backend",
      cwd: "./apps/pos-api",
      script: "node",
      args: "server.js",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 5000,
      env: { NODE_ENV: "production" },
    },
    {
      name: "pos-frontend",
      cwd: "./apps/pos",
      script: "node",
      args: "node_modules/next/dist/bin/next start -p 4000",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 8000,
      env: { NODE_ENV: "production" },
    },
    {
      name: "storefront",
      cwd: "./apps/storefront",
      script: "node",
      args: "node_modules/next/dist/bin/next start -p 3000",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 8000,
      env: { NODE_ENV: "production" },
    },
    {
      name: "admin",
      cwd: "./apps/admin",
      script: "node",
      args: "node_modules/next/dist/bin/next start -p 3001",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 8000,
      env: { NODE_ENV: "production" },
    },
    {
      name: "main-api",
      cwd: "./apps/main-api",
      script: "node",
      args: "src/server.js",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 5000,
      env: { NODE_ENV: "production" },
    },
    {
      name: "mcp",
      cwd: "./apps/mcp",
      script: "node",
      args: "dist/index.js",
      autorestart: true,
      max_restarts: 10,
      kill_timeout: 5000,
      env: { NODE_ENV: "production" },
    },
  ],
};
