import { Roboto } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/providers/store-provider";
import { Toaster } from "sonner";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "PaharTheke",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <StoreProvider>
          {children}
          <Toaster position="top-right" richColors closeButton
            toastOptions={{ className: "rounded-xl" }}
          />
        </StoreProvider>
      </body>
    </html>
  );
}
