services:
  mongo:
    image: mongo:7
    container_name: pahar-pos-mongo
    restart: unless-stopped
    command: mongod --auth
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - mongo-pos-data:/data/db

volumes:
  mongo-pos-data:
