services:
  mongodb:
    image: mongo:7
    container_name: pahartheke-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - pahartheke-network

volumes:
  mongo-data:
    driver: local

networks:
  pahartheke-network:
    driver: bridge